nav:
  - Home: index.md
  - Primeiros passos: primeiros_passos.md 
      #- Registro: primeiros_passos/registro.md
  - Como se registrar: como_se_registrar.md
  - LIneA Science Platform: 
      - LIneA Science Platform: lsp/index.md #intro e landing page
      - JupyterHub: lsp/jupyter.md
      - Science Server: lsp/sci_server.md
      - User Query: lsp/usr_query.md
  - Portais Científicos:
      - Portais Científicos: portals/index.md 
      - DES Science Portal: portals/des.md
      - TNO Portal: portals/tno.md
      - MaNGA Portal: portals/manga.md 
  - High-Performance Computing:
      - Apolo (LIneA): hpc/apolo.md
      - Santos Dumont (LNCC): hpc/sdu.md
  - Políticas: 'politicas.md'
  #- Photoz Server: 'photozserver.md'
  #- Armazenamento: 'armazenamento.md'
  #- Monitoramento: 'monitoramento.md'
  - Acrônimos: 'acronimos.md'
  - Suporte: 'suporte.md'
      - FAQ: 'faq.md'
  - Mkdocs Exemplos: 'exemplos/exemplos.md' #provisorio
  


# Site information
site_name: LIneA Docs (beta)
site_author: LIneA team 
site_url: "http://docs.linea.org.br"
repo_name: linea-it/docs
repo_url: https://github.com/linea-it/docs
edit_uri: 'edit/master/docs'
use_directory_urls: false
copyright: 'Copyright &copy; 2006 - 2022 LIneA'
# cosmo, material-components, cerulean, journal, slate, readthedocs, readable, spacelab, united, bootstrap, simplex, flatly, yeti, psinder, amelia, cyborg, unidata, mkdocs


# Configuration
theme:
  name: material
  custom_dir: linea-theme
  logo: 'images/logo_fundo_preto.png' #provisório, substituir por logo fundo transparente
  favicon: 'images/favicon.png'
  features:
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

extra:
  palette:
    primary: 'grey'
    accent: 'light blue'
  social:
    - icon: material/home-circle
      link: https://www.linea.org.br
    - icon: fontawesome/brands/github
      link: https://github.com/linea-it
    - icon: material/twitter
      link: https://twitter.com/linea_org
    - icon: material/instagram
      link: https://instagram.com/linea_org
    - icon: material/facebook
      link: https://facebook.com/linea.org
    - icon: material/youtube
      link: https://youtube.com/user/lineamcti

# Extensions
markdown_extensions:
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
